### ISSUE TITLE
Does it support applying array of instructions at once?

### ISSUE THREAD

**Issue by av0c0der** [samsonjs/LayerVideoCompositor#2]
Thank you for this convenience classes. I tried to apply multiple overlays for a video and created array of instructions as in your demo project, but asset exporter return an error (The video could not be composed).

Can you please guide me how can I achieve this? I need to different overlays at different time ranges.

```swift
var instructions: [LayerVideoCompositionInstruction] = []
let duration = CMTime(seconds: 1, preferredTimescale: 1)
var lastTimeRange = CMTimeRange(start: kCMTimeZero, duration: duration)

for overlay in overlays {
  let timeRange = CMTimeRange(start: lastTimeRange.end, duration: duration)
  let overlayLayer = newOverlayLayer(size: sourceVideoTrack.naturalSize, text: overlay)
  let instruction = LayerVideoCompositionInstruction(track: sourceVideoTrack, timeRange: timeRange, overlayLayer: overlayLayer, transform: sourceVideoTrack.preferredTransform, targetSize: sourceVideoTrack.naturalSize)
  instructions.append(instruction)
      
  lastTimeRange = timeRange
}

videoComposition.instructions = instructions
```

**Comment by samsonjs** [comment]
I think that's pretty close. Looks like you have an off-by-one error in your time ranges. The first range you use in the loop is [1, 1] instead of [0, 1]. That may be it, or it may not. AVFoundation errors are vague. Good luck!
